{{- if .Values.operator.createCommon }}
# ServiceAccount for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-system
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
# ServiceAccount for OSD pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
# ServiceAccount for MGR pods  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
# ServiceAccount for MDS pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mds
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
# ServiceAccount for RGW pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-rgw
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
# ServiceAccount for CSI driver pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace: {{ .Values.operator.namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
# Main ClusterRole for rook-ceph-system
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/proxy", "services", "endpoints", "persistentvolumes", "persistentvolumeclaims", "events", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["daemonsets", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["ceph.rook.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rook.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["policy", "apps", "extensions"]
  resources: ["poddisruptionbudgets", "deployments", "replicasets"]
  verbs: ["*"]
- apiGroups: ["healthchecking.openshift.io"]
  resources: ["machinedisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["machine.openshift.io"]
  resources: ["machines"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments", "csinodes", "csidrivers"]
  verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingadmissionwebhooks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotclasses", "volumesnapshotcontents", "volumegroupsnapshots", "volumegroupsnapshotclasses", "volumegroupsnapshotcontents"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["groupsnapshot.storage.k8s.io"]
  resources: ["volumegroupsnapshots", "volumegroupsnapshotclasses", "volumegroupsnapshotcontents"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# ClusterRole for OSD management
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-osd
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
# ClusterRole for MGR daemon
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events", "persistentvolumes", "nodes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: {{ .Values.operator.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-osd
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: {{ .Values.operator.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: {{ .Values.operator.namespace }}
{{- end }}
