# Complete Rook CRDs for Ceph
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephclusters.ceph.rook.io
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  group: ceph.rook.io
  names:
    kind: CephCluster
    listKind: CephClusterList
    plural: cephclusters
    singular: cephcluster
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              cephVersion:
                type: object
                properties:
                  image:
                    type: string
                  allowUnsupported:
                    type: boolean
              dataDirHostPath:
                type: string
              dashboard:
                type: object
                properties:
                  enabled:
                    type: boolean
                  port:
                    type: integer
                  ssl:
                    type: boolean
                  urlPrefix:
                    type: string
              mon:
                type: object
                properties:
                  count:
                    type: integer
                  allowMultiplePerNode:
                    type: boolean
              mgr:
                type: object
                properties:
                  count:
                    type: integer
                  allowMultiplePerNode:
                    type: boolean
                  modules:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        enabled:
                          type: boolean
              storage:
                type: object
                properties:
                  useAllNodes:
                    type: boolean
                  useAllDevices:
                    type: boolean
                  deviceFilter:
                    type: string
                  config:
                    type: object
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        devices:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
              placement:
                type: object
              resources:
                type: object
              priorityClassNames:
                type: object
              cleanupPolicy:
                type: object
              healthCheck:
                type: object
              disruptionManagement:
                type: object
              network:
                type: object
              security:
                type: object
          status:
            type: object
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephblockpools.ceph.rook.io
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  group: ceph.rook.io
  names:
    kind: CephBlockPool
    listKind: CephBlockPoolList
    plural: cephblockpools
    singular: cephblockpool
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              failureDomain:
                type: string
              replicated:
                type: object
                properties:
                  size:
                    type: integer
              erasureCoded:
                type: object
              mirroring:
                type: object
              quotas:
                type: object
              parameters:
                type: object
              statusCheck:
                type: object
          status:
            type: object
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephfilesystems.ceph.rook.io
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  group: ceph.rook.io
  names:
    kind: CephFilesystem
    listKind: CephFilesystemList
    plural: cephfilesystems
    singular: cephfilesystem
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              metadataPool:
                type: object
                properties:
                  replicated:
                    type: object
                    properties:
                      size:
                        type: integer
              dataPools:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    replicated:
                      type: object
                      properties:
                        size:
                          type: integer
              metadataServer:
                type: object
                properties:
                  activeCount:
                    type: integer
                  activeStandby:
                    type: boolean
                  resources:
                    type: object
              preserveFilesystemOnDelete:
                type: boolean
          status:
            type: object
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstores.ceph.rook.io
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStore
    listKind: CephObjectStoreList
    plural: cephobjectstores
    singular: cephobjectstore
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstoreusers.ceph.rook.io
  labels:
    operator: rook
    storage-backend: ceph
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStoreUser
    listKind: CephObjectStoreUserList
    plural: cephobjectstoreusers
    singular: cephobjectstoreuser
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
    subresources:
      status: {}
