# CSI Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-csi-config
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
data:
  csi-cluster-config-json: |
    []
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-csi-encryption-kms-config
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
data:
  config.json: |
    {}
---
# CSI Driver object for RBD
{{- if .Values.operator.csi.enableRBD }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: rook-ceph.rbd.csi.ceph.com
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
{{- end }}
---
# CSI Driver object for CephFS  
{{- if .Values.operator.csi.enableCephFS }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: rook-ceph.cephfs.csi.ceph.com
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
  - Persistent
{{- end }}
---
# Service for metrics
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Values.operator.namespace }}
  labels:
    app: rook-ceph-mgr
    rook_cluster: {{ .Values.operator.namespace }}
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  ports:
  - name: http-metrics
    port: 9283
    protocol: TCP
    targetPort: 9283
  - name: dashboard
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: rook-ceph-mgr
    rook_cluster: {{ .Values.operator.namespace }}
  sessionAffinity: None
  type: ClusterIP
---
# Service for mon endpoints
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mon-endpoints
  namespace: {{ .Values.operator.namespace }}
  labels:
    app: rook-ceph-mon
    mon_cluster: {{ .Values.operator.namespace }}
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: msgr1
    port: 6789
    protocol: TCP
    targetPort: 6789
  - name: msgr2
    port: 3300
    protocol: TCP  
    targetPort: 3300
  selector:
    app: rook-ceph-mon
    mon_cluster: {{ .Values.operator.namespace }}
  sessionAffinity: None
  type: ClusterIP
