{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rook-ceph-cluster.fullname" . }}-endpointslice
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rook-ceph-cluster.fullname" . }}-endpointslice
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rook-ceph-cluster.fullname" . }}-endpointslice
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: {{ .Values.operator.namespace }}
{{- end }}
